- name: docker stop all container
  shell: docker stop $(docker ps -q)
  ignore_errors: true

- name: docker remove all container
  shell: docker rm -f $(docker ps -aq)
  ignore_errors: true

- name: remove all docker images
  shell: docker rmi -f $(docker images -q)
  ignore_errors: true
  
